fitness/config/routes.rb
Fitness::Application.routes.draw do

  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :trackers, only: [:show, :create, :update, :destroy]
  resources :challenges, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      patch :add_user
      patch :remove_user
    end
    resources :messages
  end

  root to: 'static_pages#home'
  match '/home',    to: 'static_pages#home',    via: 'get'  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/dashboard', to: 'users#show', via: 'get'
  match '/settings', to: 'users#edit', via: 'get'

end

fitness/app/models/tracker.rb
class Tracker < ActiveRecord::Base
	belongs_to :user
	belongs_to :challenge
	has_many :points, dependent: :destroy

	before_save do 
		self.title = title.downcase
		self.units = units.pluralize
		self.units = self.units.downcase
		if self.aux_units != nil 
			self.aux_units = aux_units.pluralize
			self.aux_units = self.aux_units.downcase
		end
		start_before_end
	end

	default_scope -> { order('updated_at DESC') }
	validates :user_id, presence: true
	validates :title, presence: true, 
					  length: { minimum: 1, maximum: 30 }, 
					  uniqueness: { :scope => :user_id, :case_sensitive => false },
					  format: { with: /\A[a-z0-9\s]{1,30}\z/i }
	# TODO: why doesn't this work? validates :goal, format: { with: /\A[0-9]*\z/ }


	def start_before_end	
		if (self[:start_date] < self[:end_date])
			return true
		else 
			return false
		end
	end

	def to_param
		title.downcase.gsub(' ', '-')
	end
end

fitness/app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
	before_action :signed_in_user, only: [:show, :create, :update, :destroy]
	before_action :correct_user, only: [:show, :update, :destroy]

	def show 
		@user = current_user
	end

	def create
		@tracker = current_user.trackers.build(tracker_params)
		if @tracker.save
			flash[:success] = "Tracker created"
		else
			flash[:error] = "Couldn't create tracker. Make sure title is unique and all required fields are entered properly."
		end
		redirect_to dashboard_path
	end

	def update
		@point = @tracker.points.build(point_params)
		@point.save
		redirect_to :back
	end

	def destroy
		@tracker.destroy
		redirect_to dashboard_path
	end

	private
		def tracker_params
			params.require(:tracker).permit(:title, :start_date, 
				:end_date, :units, :goal, :aux_units, :aux_goal, :category, :challenge_id)
		end

		def from_param(param)
			param.gsub('-', ' ')
		end

		def point_params
			params.permit(:data, :aux_data, :created_at)
		end

		def correct_user
			@tracker = current_user.trackers.find_by_title!(from_param(params[:id]))
			redirect_to dashboard_path if @tracker.nil?
		end
end

fitness/app/views/trackers/_big_vis.html.erb
<script style="text/javascript">

	// Dimensions and colors
	var w = 500;
	var h = 350;
	var legW = 130;

	var xPadding = 45;
	var yPadding = 20;
	var curY = yPadding + 25;

	var mainCircleColor = "#3FB8AF";
	var highlightColor = "#FF3D7F";
	var opacity = 1;

	var progressWidth = 75;
	var progressHeight = 120;


	// Read the data into an array
	dataset = [];
	<% tracker.points.each do |p| %>
		var curPoint = [];
		curPoint.push(<%= p.created_at.strftime('%s') %>);
		curPoint.push(<%= p.data %>);
		dataset.push(curPoint);
	<% end %>

	generateVis(dataset);

	// Create the visualization with the given dataset
	function generateVis(dataset) {
		var xScale = d3.scale.linear()
							 .domain([d3.min(dataset, function(d) { return d[0]; })-1,
									  d3.max(dataset, function(d) { return d[0]; })+1])
							 .range([xPadding, w - xPadding]);

		var maxY = d3.max(dataset, function(d) { return d[1]; });
		<% if tracker.goal != nil %>
			var datasetWithGoal = dataset.slice(0);
			datasetWithGoal.push([0, <%=tracker.goal%>]);
			maxY = d3.max(datasetWithGoal, function(d) { return d[1]; });
		<% end %>
		var yScale = d3.scale.linear()
							 .domain([0, maxY])
							 .range([h - yPadding, yPadding]);

		
		var radius = 8;

		var lineFunction = d3.svg.line()
		                          .x(function(d) { return xScale(d[0]); })
		                          .y(function(d) { return yScale(d[1]); })
		                          .interpolate("linear");

		var formatAsDate = function(d) { 
			var date = new Date(null);  
			date.setTime(d * 1000);
			return date.toLocaleDateString();
		};
		var formatAsUnits = function(d) { return d; };


		// Create SVG element
		var svg = d3.select("#big-svg-container-" + "<%= tracker.id %>")
					.append("svg")
					.attr("id", "svg" + <%= tracker.id %>)
					.attr("width", w)
					.attr("height", h);


		// Define X axis
		var xAxis = d3.svg.axis()
						  .scale(xScale)
						  .orient("bottom")
						  .ticks(5)
						  .tickFormat(formatAsDate);

		// Define Y axis
		var yAxis = d3.svg.axis()
						  .scale(yScale)
						  .orient("left")
						  .ticks(10)
						  .tickFormat(formatAsUnits);

		// Y axis label
		svg.append("text")
			.attr("id", "y-axis-label")
			.attr("class", "axis-label")
	        .attr("x", 0-(h/2))
	        .attr("y", 10)
	        .attr("transform", "rotate(-90) translate(0, 0)")
	        .style("text-anchor", "middle")
	        .text('<%= tracker.units %>');


		// Draw lines connecting dots
		svg.append("path")
			.attr("d", lineFunction(dataset))
			.attr("id", "connector-path")
			.attr("stroke", mainCircleColor)
			.attr("stroke-width", 2)
			.attr("fill", "none");

		// Draw goal line if any
		<% if tracker.goal != nil %>
			svg.append("line")
				.attr("id", "goal-line")
	            .attr("x1", xScale(d3.min(dataset, function(d) { return d[0]; })-1))
	            .attr("y1", yScale(<%=tracker.goal%>))
	            .attr("x2", xScale(d3.max(dataset, function(d) { return d[0]; })+1))
	            .attr("y2", yScale(<%=tracker.goal%>))
				.attr("stroke", highlightColor)
				.attr("stroke-width", 2)
				.attr("fill", "none")
				.attr("opacity", 0.5);
		<% end %>

		// Create circles
		svg.selectAll("circle")
			.data(dataset)
			.enter()
			.append("circle")
			.attr("cx", function(d) {
		   		return xScale(d[0]);
		    })
		    .attr("cy", function(d) {
		   		return yScale(d[1]);
			})
			.attr("r", function(d) {
				return radius;
			})
			.attr("fill", function(d) {
				return mainCircleColor;
			})
			.attr("opacity", opacity)
			.on("mouseover", function(d) {

				// Change color
				d3.select(this).attr("fill", highlightColor);

				// Show the tooltip
				var xPosition = parseInt(d3.select(this).attr("cx")) + document.getElementById("svg" + <%= tracker.id %>).offsetLeft + 1.5*radius;
				var yPosition = parseInt(d3.select(this).attr("cy")) + document.getElementById("svg" + <%= tracker.id %>).offsetTop + 6*radius;
				d3.select("#tooltip")
					.style("left", xPosition + "px")
					.style("top", yPosition + "px");

				var date = new Date(null);
				date.setTime(d[0] * 1000);
				d3.select("#point-time").text(date.toLocaleString());
				d3.select("#point-value").html(d[1] + " <%= tracker.units %>");
				d3.select("#tooltip").classed("hidden", false);

				// Update goal fill
				<% if tracker.goal != nil %>
					var percent = Math.min(1, Math.max(0, (d[1] - dataset[0][1]) / (<%= tracker.goal %> - dataset[0][1])));
					d3.select("#progress-bar")
						.transition()
						.duration(80)
						.attr("height", percent * progressHeight)
						.attr("y", curY + progressHeight - (percent*progressHeight));

					d3.select("#progress-bar-text")
						.text((percent * 100).toFixed(0) + '%');
				<% end %>
			})
			.on("mouseout", function(d) {
				// Restore color
				d3.select(this).attr("fill", mainCircleColor);

				// Hide the tooltip
				d3.select("#tooltip").classed("hidden", true);

				// Update goal fill
				<% if tracker.goal != nil %>
					var percent = Math.min(1, Math.max(0, (dataset[dataset.length-1][1] - dataset[0][1]) / (<%= tracker.goal %> - dataset[0][1])));
					d3.select("#progress-bar")
						.transition()
						.duration(80)
						.attr("height", percent * progressHeight)
						.attr("y", curY + progressHeight - (percent*progressHeight));

					d3.select("#progress-bar-text")
						.text((percent * 100).toFixed(0) + '%');
				<% end %>
			});

		// Create X axis
		svg.append("g")
			.attr("class", "x axis")
			.attr("transform", "translate(0," + (h - yPadding) + ")")
			.call(xAxis);
		
		// Create Y axis
		svg.append("g")
			.attr("class", "y axis")
			.attr("transform", "translate(" + xPadding + ",0)")
			.call(yAxis);


		// Create legend SVG element
		var legSvg = d3.select("#big-svg-container-" + "<%= tracker.id %>")
				.append("svg")
				.attr("class", "leg-svg")
				.attr("id", "leg-svg" + <%= tracker.id %>)
				.attr("width", legW)
				.attr("height", h);
		legSvg.append("text")
				.attr("class", "legend-header")
				.attr("text-anchor", "middle")
				.attr("x", legW/2)
				.attr("y", yPadding)
				.text("Legend");

		

		// Add radio buttons to toggle scale between raw weight and percent change
		var rawButton = legSvg.append("g")
								.attr("class", "svg-radio-button radio-button-disabled")
								.attr("id", "raw")
								.attr("fill", "rgba(255,255,255,0)")
								.attr("transform", "translate(7," + curY + ")");
		rawButton.append("circle")
					.attr("class", "svg-radio-outer")
					.attr("r", 6)
					.attr("stroke", highlightColor)
					.attr("stroke-width", 2);
		rawButton.append("circle")
					.attr("class", "svg-radio-inner")
					.attr("r", 3)
					.attr("stroke", highlightColor)
					.attr("fill", highlightColor);
		rawButton.append("text")
					.attr("class", "legend-text")
					.attr("text-anchor", "left")
					.attr("fill", "black")
					.attr("transform", "translate(12, 5)")
					.text("Show raw data");
		var curSelection = rawButton;
		curY += 20;

		var percentButton = legSvg.append("g")
								.attr("class", "svg-radio-button radio-button-disabled")
								.attr("id", "percent")
								.attr("fill", "rgba(255,255,255,0)")
								.attr("transform", "translate(7," + curY + ")");
		percentButton.append("circle")
					.attr("class", "svg-radio-outer")
					.attr("r", 6)
					.attr("stroke", highlightColor)
					.attr("stroke-width", 2);
		percentButton.append("circle")
					.attr("class", "svg-radio-inner")
					.attr("r", 0)
					.attr("stroke", highlightColor)
					.attr("fill", highlightColor);
		percentButton.append("text")
					.attr("class", "legend-text")
					.attr("text-anchor", "left")
					.attr("fill", "black")
					.attr("transform", "translate(12, 5)")
					.text("Show % change");

		curY += 30;

		// Toggle view based on user selection
		d3.selectAll('.svg-radio-button')
			.on("click", function(d) {
				d3.select(this).select(".svg-radio-inner")
					.attr("r", 3);
				curSelection.select(".svg-radio-inner")
					.attr("r", 0);
				curSelection = d3.select(this);

				// Update y scale and circle positions
				if (curSelection.attr("id") == "raw") {
					yScale.domain([0, maxY]);
					d3.select("#goal-line").classed("hidden", false);

					svg.selectAll("circle")
						.transition()
						.duration(300)
						.attr("cy", function(d, i) {
							return yScale(d[1]);
						});

					// Update line
					lineFunction.y(function(d) {
						return yScale(d[1]);
					});


				} else {
					yScale.domain([d3.min(dataset, function(d, i) { return percentChange(d, i); }), 
						d3.max(dataset, function(d, i) { return percentChange(d, i); })]);
					d3.select("#goal-line").classed("hidden", true);

					svg.selectAll("circle")
						.transition()
						.duration(300)
						.attr("cy", function(d, i) {
							return yScale(percentChange(d, i));
						});

					// Update line
					lineFunction.y(function(d, i) {
						return yScale(percentChange(d, i));
					});
				}

				svg.select("#connector-path")
					.transition()
					.duration(300)
					.attr("d", lineFunction(dataset));

				// Update y axis 
				svg.select(".y.axis")
                    .transition()
                    .duration(300)
                    .call(yAxis);

				svg.select("#y-axis-label")
					.text((curSelection.attr("id")=="raw") ? "raw data" : "percent change");
			});

		// Draw goal legend and progress bar
		<% if tracker.goal != nil %>
			legSvg.append("rect")
					.attr("x", 1)
					.attr("y", curY)
					.attr("rx", 3)
					.attr("ry", 3)
				    .attr("width", 12)
				    .attr("height", 12)
		    		.style("fill", highlightColor)
		    		.attr("opacity", 0.5);

		    legSvg.append("text")
					.attr("class", "legend-text")
					.attr("text-anchor", "left")
					.attr("x", 17)
					.attr("y", curY + 9)
					.text("goal: <%= tracker.goal.round(2) %> <%= tracker.units %>");
			curY += 30;

			var percent = Math.min(1, Math.max(0, (dataset[dataset.length-1][1] - dataset[0][1]) / (<%= tracker.goal %> - dataset[0][1])));
			legSvg.append("rect")
					.attr("x", legW / 2 - progressWidth / 2)
					.attr("y", curY)
					.attr("rx", 3)
					.attr("ry", 3)
					.attr("width", progressWidth)
					.attr("height", progressHeight)
					.attr("stroke", highlightColor)
					.attr("stroke-width", 2)
					.attr("fill", "white")
					.attr("opacity", 0.5);

			legSvg.append("rect")
					.attr("id", "progress-bar")
					.attr("x", legW / 2 - progressWidth / 2)
					.attr("y", curY + progressHeight - (percent*progressHeight))
					.attr("rx", 3)
					.attr("ry", 3)
					.attr("width", progressWidth)
					.attr("height", percent*progressHeight)
					.attr("stroke", "none")
					.attr("fill", highlightColor)
					.attr("opacity", 0.5);
			legSvg.append("text")
					.attr("id", "progress-bar-text")
					.attr("text-anchor", "middle")
					.attr("x", legW / 2)
					.attr("y", curY + 20)
					.text((percent * 100).toFixed(0) + '%');

		<% end %>
	}

	function percentChange(d, i) {
		var percentChange = 0;
		if (i > 0) percentChange = (d[1] - dataset[i-1][1]) / dataset[i-1][1] * 100;
		return percentChange;
	}

</script>

fitness/app/views/trackers/_custom_edit_form.html.erb
<h3 class="center tracker-title"><%= tracker.title %></h3>

<%= form_for(tracker, class: "tracker-form") do |f| %>
	<%= f.text_field :title, placeholder: "Title", class: "input-field", maxlength: "30" %>
	<%= f.text_field :units, placeholder: "Units", class: "input-field" %>
	<%= f.text_field :goal, placeholder: "Goal", class: "input-field", onkeypress: "return isNumberKey(event)" %>
	<table>
		<tr>
			<td class="vert-center"><%= f.label :start_date %></td>
			<td class="date-field"><%= f.date_field :start_date, placeholder: "Start date", class: "input-field" %></td>
		</tr>
		<tr>
			<td class="vert-center"><%= f.label :end_date %></td>
			<td class="date-field"><%= f.date_field :end_date, placeholder: "End date", class: "input-field" %></td>
		</tr>
	</table>
	<div class="center-container"><%= f.submit "Save", class: "button tracker-form-button" %></div>
<% end %>

fitness/app/views/trackers/_custom_form.html.erb
<%= form_for(@new_tracker, class: "tracker-form") do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.text_field :title, placeholder: "Title", class: "input-field required", maxlength: "30" %>
	<%= f.text_field :units, placeholder: "Units", class: "input-field required" %>
	<%= f.text_field :goal, placeholder: "Goal", class: "input-field", onkeypress: "return isNumberKey(event)" %>
	<table>
		<tr>
			<td class="vert-center"><%= f.label :start_date %></td>
			<td class="date-field"><%= f.date_field :start_date, placeholder: "Start date", class: "input-field" %></td>
		</tr>
		<tr>
			<td class="vert-center"><%= f.label :end_date %></td>
			<td class="date-field"><%= f.date_field :end_date, placeholder: "End date", class: "input-field" %></td>
		</tr>
	</table>
	<%= f.hidden_field :category, :value => "custom" %>
	<div class="center-container"><%= f.submit "Create", class: "button tracker-form-button" %></div>
<% end %>

fitness/app/views/trackers/_distance_form.html.erb
<%= form_for(@new_tracker, class: "tracker-form") do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.text_field :title, placeholder: "Title", class: "input-field required", maxlength: "30" %>
	<%= f.text_field :units, placeholder: "Distance Units (i.e. miles)", class: "short-input-field required" %>
	<%= f.text_field :aux_units, placeholder: "Time Units (i.e. minutes)", class: "short-input-field pull-right required" %>
	<%= f.text_field :goal, placeholder: "Distance Goal", class: "short-input-field", onkeypress: "return isNumberKey(event)"  %>
	<%= f.text_field :aux_goal, placeholder: "Time Goal", class: "short-input-field pull-right", onkeypress: "return isNumberKey(event)"  %>
	<table>
		<tr>
			<td class="vert-center"><%= f.label :start_date %></td>
			<td class="date-field"><%= f.date_field :start_date, placeholder: "Start date", class: "input-field" %></td>
		</tr>
		<tr>
			<td class="vert-center"><%= f.label :end_date %></td>
			<td class="date-field"><%= f.date_field :end_date, placeholder: "End date", class: "input-field" %></td>
		</tr>
	</table>
	<%= f.hidden_field :category, :value => "distance" %>
	<div class="center-container"><%= f.submit "Create", class: "button tracker-form-button" %></div>
<% end %>

fitness/app/views/trackers/_lift_form.html.erb
<%= form_for(@new_tracker, class: "tracker-form") do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.text_field :title, placeholder: "Title", class: "input-field required", maxlength: "30" %>
	<%= f.hidden_field :units, :value => "reps" %>
	<%= f.text_field :aux_units, placeholder: "Weight Units (i.e. pounds)", class: "input-field required" %>
	<%= f.text_field :goal, placeholder: "Reps Goal", class: "short-input-field", onkeypress: "return isNumberKey(event)"  %>
	<%= f.text_field :aux_goal, placeholder: "Weight Goal", class: "short-input-field pull-right", onkeypress: "return isNumberKey(event)"  %>
	<table>
		<tr>
			<td class="vert-center"><%= f.label :start_date %></td>
			<td class="date-field"><%= f.date_field :start_date, placeholder: "Start date", class: "input-field" %></td>
		</tr>
		<tr>
			<td class="vert-center"><%= f.label :end_date %></td>
			<td class="date-field"><%= f.date_field :end_date, placeholder: "End date", class: "input-field" %></td>
		</tr>
	</table>
	<%= f.hidden_field :category, :value => "lift" %>
	<div class="center-container"><%= f.submit "Create", class: "button tracker-form-button" %></div>
<% end %>

fitness/app/views/trackers/_tracker.html.erb
<script language="javascript" type="text/javascript">

</script>

<% if tracker.title != nil %>
<li class="tracker-tile tile" id=<%= "tracker-tile-#{tracker.id}" %>>
	<% if tracker.challenge_id == nil %>
		<h3 class="center tracker-title"><%= tracker.title %></h3>
		<span class="center tracker-challenge-subtitle"></span>
	<% else %>
		<h3 class="center tracker-title"><%= link_to tracker.title[0..tracker.title.length-11], Challenge.find_by(id: tracker.challenge_id) %></h3>
		<span class="center tracker-challenge-subtitle">(Challenge)</span>
	<% end %>

	<% if tracker.points.any? %>
		<div class="tracker-vis-container" id=<%= "tracker-vis-container-#{tracker.id}" %>>
			<div id="tooltip" class="hidden">
				<span id="point-time"></span><br/>
				<span id="point-value"></span>
			</div>

			<%= link_to(tracker) do %>
			  <div class="mini-svg-container" id=<%= "mini-svg-container-#{tracker.id}" %>></div>
			<% end %>
			<%= render 'trackers/mini_vis', :tracker => tracker %>
			
		</div>
	<% end %>

	<% if current_user?(tracker.user) %>
		<div class="log-form-container">
			<% if tracker.category == 'custom' || tracker.category == 'weight' %>
				<%= form_for(tracker) do |f| %>
					<%= text_field_tag :data, nil, :class => 'input-field', :placeholder => tracker.units, onkeypress: "return isNumberKey(event)" %>
					<%= f.submit "Log", class: "button log-button" %>
				<% end %>
			<% else %>
				<%= form_for(tracker) do |f| %>
					<%= text_field_tag :data, nil, :class => 'short-input-field', :placeholder => tracker.units, onkeypress: "return isNumberKey(event)" %>
					<%= text_field_tag :aux_data, nil, :class => 'short-input-field', :placeholder => tracker.aux_units, onkeypress: "return isNumberKey(event)" %>
					<%= f.submit "Log", class: "button log-button" %>
				<% end %>
			<% end %>
		</div>

		<div class="tile-icons-container hidden">
			<!-- %= image_tag('settings-icon.png', class: "tile-icon settings-tile-icon") % -->
			<%= link_to image_tag('graph-icon.png'), tracker, class: "tile-icon" %>
			<% if tracker.challenge_id == nil %>
				<%= link_to image_tag('trash-icon.png'), tracker, class: "tile-icon", method: :delete, data: { confirm: "Are you sure? This will permanently delete this tracker and all of its associated data." }, title: tracker.title %>
			<% else %>
				<%= link_to image_tag('trash-icon.png'), remove_user_challenge_path(Challenge.find_by(id: tracker.challenge_id)), class: "tile-icon", method: 'patch', confirm: "Are you sure? This will permanently delete this tracker and remove you from the associated challenge group." %>
			<% end %>
		</div>		
	<% end %>
	
</li>
<% end %> 

fitness/app/views/trackers/_weight_form.html.erb
<%= form_for(@new_tracker, class: "tracker-form") do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.text_field :title, placeholder: "Title", class: "input-field required", maxlength: "30" %>
	<%= f.text_field :units, placeholder: "Units", class: "input-field required" %>
	<%= f.text_field :goal, placeholder: "Goal", class: "input-field", onkeypress: "return isNumberKey(event)"  %>
	<table>
		<tr>
			<td class="vert-center"><%= f.label :start_date %></td>
			<td class="date-field"><%= f.date_field :start_date, placeholder: "Start date", class: "input-field" %></td>
		</tr>
		<tr>
			<td class="vert-center"><%= f.label :end_date %></td>
			<td class="date-field"><%= f.date_field :end_date, placeholder: "End date", class: "input-field" %></td>
		</tr>
	</table>
	<%= f.hidden_field :category, :value => "weight" %>
	<div class="center-container"><%= f.submit "Create", class: "button tracker-form-button" %></div>
<% end %>

fitness/app/views/trackers/show.html.erb
<% provide(:title, "Dashboard") %>
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>

<table id="dashboard-container" border="none" width="100%">
	<tr>
		<td id="trackers-container" width="99%">
			<div id="big-vis-container" class="tile" id=<%= "big-vis-container-#{@tracker.id}" %>>
				<% if @tracker.challenge_id == nil %>
					<h3 class="center tracker-title"><%= @tracker.title %></h3>
					<span class="center tracker-challenge-subtitle"></span>
				<% else %>
					<h3 class="center tracker-title"><%= link_to @tracker.title[0..@tracker.title.length-11], Challenge.find_by(id: @tracker.challenge_id) %></h3>
					<span class="center tracker-challenge-subtitle">(Challenge)</span>
				<% end %>

				<% if @tracker.points.any? %>
					<div id="tooltip" class="hidden">
						<span id="point-time"></span><br/>
						<span id="point-value"></span>
					</div>

					<div class="big-svg-container" id=<%= "big-svg-container-#{@tracker.id}" %>></div>
					<% if @tracker.category == 'distance' %>
						<%= render 'trackers/big_vis_distance', :tracker => @tracker %>
					<% elsif @tracker.category == 'lift' %>
						<%= render 'trackers/big_vis_lift', :tracker => @tracker %>
					<% else %>
						<%= render 'trackers/big_vis', :tracker => @tracker %>
					<% end %>
				<% end %>

				<% if current_user?(@tracker.user) %>
					<div id="big-log-form-container">
						<% if @tracker.category == 'custom' || @tracker.category == 'weight' %>
							<%= form_for(@tracker, :class=>"big-log-form") do |f| %>
								<%= text_field_tag :data, nil, :class => 'short-input-field', :placeholder => @tracker.units, onkeypress: "return isNumberKey(event)" %>
								<!--%= date_field_tag :created_at, nil, :class => 'short-input-field' %-->
								<%= f.submit "Log", class: "button log-button" %>
								<span class="last-log">Last log: <%= time_ago_in_words(@tracker.updated_at) %> ago</span>
							<% end %>
						<% else %>
							<%= form_for(@tracker, :class=>"big-log-form") do |f| %>
								<%= text_field_tag :data, nil, :class => 'short-input-field', :placeholder => @tracker.units, onkeypress: "return isNumberKey(event)" %>
								<%= text_field_tag :aux_data, nil, :class => 'short-input-field', :placeholder => @tracker.aux_units, onkeypress: "return isNumberKey(event)" %>
								<!--%= date_field_tag :created_at, nil, :class => 'short-input-field' %-->
								<%= f.submit "Log", class: "button log-button" %>
								<span class="last-log">Last log: <%= time_ago_in_words(@tracker.updated_at) %> ago</span>
							<% end %>
						<% end %>
						
					</div>	
				<% end %>
			</div>
		</td>

		<td id="challenges-container" style="white-space: nowrap;">
			<div id="challenges-tile" class="tile">
				<h3 class="center">Challenges</h3>
				<a href=<%= new_challenge_path %>><button>New Challenge</button></a>

				<% if @user.challenges.any? %>
					<ul id="challenges-list">
						<%= render @user.challenges %>
					</ul>
				<% end %>
			</div>
		</td>
	</tr>
	

</table>