fitness/config/routes.rb
Fitness::Application.routes.draw do

  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :trackers, only: [:show, :create, :update, :destroy]
  resources :challenges, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      patch :add_user
      patch :remove_user
    end
    resources :messages
  end

  root to: 'static_pages#home'
  match '/home',    to: 'static_pages#home',    via: 'get'  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/dashboard', to: 'users#show', via: 'get'
  match '/settings', to: 'users#edit', via: 'get'

end

fitness/app/models/user.rb
class User < ActiveRecord::Base
    has_many :trackers, dependent: :destroy
    has_many :messages, dependent: :destroy
    has_and_belongs_to_many :challenges

	before_save { self.email = email.downcase }
	before_create :create_remember_token

	validates :name, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, 
  		format: { with: VALID_EMAIL_REGEX },
    	uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, length: { minimum: 6 }

    def User.new_remember_token
    	SecureRandom.urlsafe_base64
    end

    def User.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
    end

    private
    	def create_remember_token
    		self.remember_token = User.encrypt(User.new_remember_token)
    	end
    	
end

fitness/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:update, :destroy]
  before_action :correct_user, only: [:update, :destroy]

  def show
    @user = current_user
    @new_tracker = @user.trackers.build
  end

  def new
    if signed_in?
      redirect_to dashboard_path
    else
      @user = User.new
    end
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
  		flash[:success] = "Welcome!"
  		redirect_to dashboard_path
  	else
  		render 'new'
  	end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to dashboard_path
    else
      render 'edit'
    end
  end

  def destroy
    current_user.destroy
    flash[:success] = "User deleted"
    redirect_to root_url
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, 
  			:password, :password_confirmation)
  	end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(dashboard_path) unless current_user?(@user)
    end

end

fitness/app/helpers/users_helper.rb
module UsersHelper
end

fitness/app/views/users/_user.html.erb
<li>
	<%= user.name %>, <%= link_to user.email, "mailto:"+user.email %>
</li>

fitness/app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<div class="sign-page-container">
	<div class="sign-form-container white-transparent-form">
		<h2 class="center">Update your profile</h2>

		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: "input-field" %><br/>

			<%= f.label :email %>
			<%= f.text_field :email, class: "input-field" %><br/>

			<%= f.label :password %>
			<%= f.password_field :password, class: "input-field" %><br/>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: "input-field" %><br/>

			<%= f.submit "Save changes", class: "button sign-submit-button" %>

		<% end %>
	</div>

</div>

fitness/app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<div class="sign-page-container" class="static-page-container">
	<div class="sign-form-container white-transparent-form">
		<h2 class="center">Sign Up</h2>

		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: "input-field" %><br/>

			<%= f.label :email %>
			<%= f.text_field :email, class: "input-field" %><br/>

			<%= f.label :password %>
			<%= f.password_field :password, class: "input-field" %><br/>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: "input-field" %><br/>

			<%= f.submit "Sign Up", class: "button sign-submit-button" %>

		<% end %>

		<p>Already registered? <%= link_to "Sign in here!", signin_path %></p>
	</div>

</div>

fitness/app/views/users/show.html.erb
<% provide(:title, "Dashboard") %>
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>

<script language="javascript" type="text/javascript">
	jQuery(function($) {
		$('#tracker-select').on('change', function() {
			$("#tracker-form-container").html("");

			if ($("#tracker-select").val() == 'weight') {
				$("#tracker-form-container").append("<%= escape_javascript render(:partial => 'trackers/weight_form') %>");
			} else if ($("#tracker-select").val() == 'lifting') {
				$("#tracker-form-container").append("<%= escape_javascript render(:partial => 'trackers/lift_form') %>");
			} else if ($("#tracker-select").val() == 'running' || $("#tracker-select").val() == 'biking') {
				$("#tracker-form-container").append("<%= escape_javascript render(:partial => 'trackers/distance_form') %>");
			} else if ($("#tracker-select").val() == 'custom') {
				$("#tracker-form-container").append("<%= escape_javascript render(:partial => 'trackers/custom_form') %>");
			} 
			
		});

		$('.tracker-tile').on('mouseover', function() {
			$(this).find('.tile-icons-container').removeClass('hidden');
		});

		$('.tracker-tile').on('mouseout', function() {
			$(this).find('.tile-icons-container').addClass('hidden');
		});
	});

</script>

<div id="overlay" class="hidden">
	<div id="big-vis-container"></div>
</div>

<table id="dashboard-container" border="none">
	<tr>
		<td id="trackers-container">
			<div class="tracker-tile tile">
				<h3 class="center">Create new tracker</h3>
				<div class="center-container">
					<select id="tracker-select">
						<option value="blank"></option>
						<option value="weight">Weight Loss/Gain</option>
						<option value="lifting">Weight Lifting</option>
						<option value="running">Running</option>
						<option value="biking">Biking</option>
						<option value="custom">Custom</option>
					</select>
				</div>
				<div id="tracker-form-container"></div>
			</div>

			<% if @user.trackers.any? %>
				<ul id="trackers-list">
					<%= render @user.trackers %>
				</ul>
			<% end %>
		</td>

		<td id="challenges-container">
			<div id="challenges-tile" class="tile">
				<h3 class="center">Challenges</h3>
				<a href=<%= new_challenge_path %>><button>New Challenge</button></a>

				<% if @user.challenges.any? %>
					<ul id="challenges-list">
						<%= render @user.challenges %>
					</ul>
				<% end %>
			</div>
		</td>
	</tr>
	

</table>