fitness/config/routes.rb
Fitness::Application.routes.draw do

  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :trackers, only: [:show, :create, :update, :destroy]
  resources :challenges, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      patch :add_user
      patch :remove_user
    end
    resources :messages
  end

  root to: 'static_pages#home'
  match '/home',    to: 'static_pages#home',    via: 'get'  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/dashboard', to: 'users#show', via: 'get'
  match '/settings', to: 'users#edit', via: 'get'

end

fitness/app/models/challenge.rb
class Challenge < ActiveRecord::Base
	validates :title, presence: true, 
					  length: { minimum: 1, maximum: 30 },
					  format: { with: /\A[a-z0-9\s]{1,30}\z/i }
	validates :start_date, presence: true
	validates :end_date, presence: true
	validates :units, presence: true

	has_and_belongs_to_many :users
	has_many :trackers
	has_many :messages, dependent: :destroy

	before_save do 
		self.title = title.downcase
		start_before_end
	end


	def start_before_end	
		if (self[:start_date] < self[:end_date])
			return true
		else 
			return false
		end
	end
end

fitness/app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
	before_action :signed_in_user, only: [:show, :new, :edit, :create, :update, :add_user, :remove_user, :destroy]
	before_action :member_user,   only: [:show, :edit, :update, :add_user, :remove_user, :destroy]

	def show
		@tracker = current_user.trackers.find_by_challenge_id(@challenge.id)
	end

	def new
		@challenge = Challenge.new
	end

	def create
		@challenge = Challenge.new(challenge_params)
		if @challenge.save
			@challenge.users << current_user
			@new_tracker = current_user.trackers.build(:title=>@challenge.title+' challenge', 
				:start_date=>@challenge.start_date, :end_date=>@challenge.end_date,
				:units=>@challenge.units, :challenge_id=>@challenge.id, :category=>'custom')
			@new_tracker.save
			flash[:success] = "Challenge created!"
			redirect_to @challenge
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @challenge.update_attributes(challenge_params)
			flash[:success] = "Challenge updated"
			redirect_to @challenge
		else
			render 'edit'
		end
	end

	def add_user
		@other_user = User.find_by_email(add_user_params[:user_email])
		if @other_user.nil?
			flash[:error] = "Invalid user email"
			redirect_to @challenge
		elsif @challenge.users.find_by(:id => @other_user.id) != nil
			flash[:error] = "User already exists in challenge"
			redirect_to @challenge
		else
			@challenge.users << @other_user
			@new_tracker = @other_user.trackers.build(:title=>@challenge.title+' challenge', 
				:start_date=>@challenge.start_date, :end_date=>@challenge.end_date,
				:units=>@challenge.units, :challenge_id=>@challenge.id, :category=>'custom')
			@new_tracker.save
			flash[:success] = "User added!"
			redirect_to @challenge
		end
	end

	def remove_user
		current_user.trackers.find_by_challenge_id(@challenge.id).destroy
		@challenge.users.delete(current_user)
		redirect_to dashboard_path
	end

	def destroy
		@challenge.destroy
		flash[:success] = "Challenge deleted"
		redirect_to dashboard_path
	end



	private
		def challenge_params
			params.require(:challenge).permit(:title, :description, :start_date, :end_date, :units, :category)
		end

		def add_user_params
			params.permit(:user_email)
		end

		def member_user
			@challenge = Challenge.find(params[:id])
			redirect_to(dashboard_path) unless @challenge.users.include? current_user
	    end
end

fitness/app/helpers/challenges_helper.rb
module ChallengesHelper
end

fitness/app/views/challenges/_challenge.html.erb
<li class="challenge-list-item">
	<span class="challenge-header"><%= link_to challenge.title, challenge %></span><br/>
	<span class="challenge-dates-container">
		<%= (challenge.start_date).strftime('%b %d, %Y') %> - <%= (challenge.end_date).strftime('%b %d, %Y') %>
	</span>
</li>

fitness/app/views/challenges/_challenge_vis.html.erb
<script style="text/javascript">

	// Dimensions and colors
	var w = 500;
	var h = 420;
	var barsW = 180;

	var xPadding = 45;
	var yPadding = 20;
	var barPadding = 3;

	var mainCircleColor = "#3FB8AF";
	var highlightColor = "#FF3D7F";
	var opacity = 1;


	// Read the data into an array
	dataset = [];
	<% challenge.users.each do |u| %>
		var curValues = [];
		<% u.trackers.find_by_challenge_id(challenge.id).points.each do |p| %>
			var curPoint = { timestamp: <%= p.created_at.strftime('%s') %>,
							 pointVal: <%= p.data %> };
			curValues.push(curPoint);
		<% end %>
		var curData = { id: <%= u.id %>,
						name: '<%= u.name %>', 
						values: curValues };
		dataset.push(curData);
	<% end %>

	// Sort the dataset in increasing order by the most recent point value
	dataset.sort(function(a, b) {
		if (a.values.length == 0) return 1;
		else if (b.values.length == 0) return -1;


		var lastAVal = a.values[a.values.length - 1].pointVal;
		var lastBVal = b.values[b.values.length - 1].pointVal;

		<% if challenge.category == 'highest_value' %>
			return lastBVal - lastAVal;
		<% elsif challenge.category == 'lowest_value' %>
			return lastAVal - lastBVal;
		<% end %>

		var firstAVal = a.values[0].pointVal;
		var firstBVal = b.values[0].pointVal;
		var aChange = lastAVal - firstAVal;
		var bChange = lastBVal - firstBVal;

		<% if challenge.category == 'greatest_increase' %>
			return bChange - aChange;
		<% elsif challenge.category == 'greatest_decrease' %>
			return aChange - bChange;
		<% elsif challenge.category == 'greatest_percent_increase' %>
			return (bChange / firstBVal) - (aChange / firstAVal);
		<% elsif challenge.category == 'greatest_percent_decrease' %>
			return (aChange / firstAVal) - (bChange / firstBVal);
		<% end %>

		var aSum = 0;
		for (var i = 0; i < a.values.length; i++) { aSum += a.values[i].pointVal; }
		var bSum = 0;
		for (var i = 0; i < b.values.length; i++) { bSum += b.values[i].pointVal; }
		<% if challenge.category == 'highest_cumulative' %>
			return bSum - aSum;
		<% elsif challenge.category == 'lowest_cumulative' %>
			return aSum - bSum;
		<% end %>
	});

	generateVis(dataset);

	// Create the visualization with the given dataset
	function generateVis(dataset) {
		// TODO: look into d3.time.scale() ?
		var date = new Date();
		var xScale = d3.scale.linear()
							 .domain([<%= challenge.start_date.strftime('%s') %> - 1,
									  Math.min(date.getTime() / 1000, <%= challenge.end_date.strftime('%s') %>)])
							 .range([xPadding, w - xPadding]);

		
		var yScale = d3.scale.linear()
							 .domain([0, d3.max(dataset, function(d) { 
							 	return d3.max(d.values, function(d) { return d.pointVal; });
							 })])
							 .range([h - yPadding, yPadding]);

		
		var radius = 8;

		var lineFunction = d3.svg.line()
		                          .x(function(d) { return xScale(d.timestamp); })
		                          .y(function(d) { return yScale(d.pointVal); })
		                          .interpolate("linear");

		var formatAsDate = function(d) { 
			date.setTime(d * 1000);
			return date.toLocaleDateString();
		};
		var formatAsUnits = function(d) { return d; };


		// Create SVG element
		var svg = d3.select("#challenge-svg-container-" + "<%= challenge.id %>")
					.append("svg")
					.attr("id", "svg" + <%= challenge.id %>)
					.attr("width", w)
					.attr("height", h);


		// Define X axis
		var xAxis = d3.svg.axis()
						  .scale(xScale)
						  .orient("bottom")
						  .ticks(5)
						  .tickFormat(formatAsDate);

		// Define Y axis
		var yAxis = d3.svg.axis()
						  .scale(yScale)
						  .orient("left")
						  .ticks(10)
						  .tickFormat(formatAsUnits);

		// Y axis label
		svg.append("text")
			.attr("id", "y-axis-label")
			.attr("class", "axis-label")
	        .attr("x", 0-(h/2))
	        .attr("y", 10)
	        .attr("transform", "rotate(-90) translate(0, 0)")
	        .style("text-anchor", "middle")
	        .text('<%= challenge.units %>');


		// Create X axis
		svg.append("g")
			.attr("class", "x axis")
			.attr("transform", "translate(0," + (h - yPadding) + ")")
			.call(xAxis);
		
		// Create Y axis
		svg.append("g")
			.attr("class", "y axis")
			.attr("transform", "translate(" + xPadding + ",0)")
			.call(yAxis);

		// Display data
		var trackerLine = svg.selectAll(".tracker-line")
							.data(dataset)
							.enter()
							.append("g")
							.attr("class", "tracker-line");
		trackerLine.append("path")
					.attr("class", "line")
					.attr("id", function(d) {
						return "tracker-line-" + d.id;
					})
					.attr("d", function(d) { return lineFunction(d.values); })
					.style("stroke", mainCircleColor)
					.attr("stroke-width", 2)
					.attr("fill", "none")
					.on("mouseover", function(d) {
						d3.select(this).style("stroke", highlightColor);

						// highlight corresponding text
						barsSvg.select("#tracker-line-name-" + d.id).style("fill", highlightColor);
					})
					.on("mouseout", function(d) {
						d3.select(this).style("stroke", mainCircleColor);
						barsSvg.select("#tracker-line-name-" + d.id).style("fill", "black");
					});

		// TODO: Create SVG to show bars for each user
		var barScale = d3.scale.linear()
					 .domain([0, d3.max(dataset, function(d) { 
					 	return d3.max(d.values, function(d) { return d.pointVal; });
					 })])
					 .range([xPadding, barsW - xPadding]);

		var barHeight = Math.min(h / dataset.length - barPadding, 50);
		var barStartY = yPadding + 30;

		var barsSvg = d3.select("#challenge-svg-container-" + "<%= challenge.id %>")
						.append("svg")
						.attr("id", "barsSvg" + <%= challenge.id %>)
						.attr("class", "barsSvg")
						.attr("width", barsW)
						.attr("height", h);

		barsSvg.selectAll("text")
			   .data(dataset)
			   .enter()
			   .append("text")
			   .text(function(d, i) {
			   		if (d.values.length == 0) return (i+1) + ". " + d.name;

			   		var value = 0;
			   		var valueString = "";
			   		var f = 0;
			   		<% if challenge.category == 'highest_value' || challenge.category == 'lowest_value' %>
			   			value = d.values[d.values.length-1].pointVal;
			   			f = (value % 1 == 0 ? 0 : 1);
			   			valueString = value.toFixed(f) + " <%= challenge.units %>";
			   		<% elsif challenge.category == 'greatest_increase' || challenge.category == 'greatest_decrease' %>
			   			value = d.values[d.values.length-1].pointVal.toFixed(f) - d.values[0].pointVal;
			   			f = (value % 1 == 0 ? 0 : 1);
			   			valueString = value.toFixed(f) + " <%= challenge.units %>";
			   		<% elsif challenge.category == 'greatest_percent_increase' || challenge.category == 'greatest_percent_decrease' %>
			   			value = ((d.values[d.values.length-1].pointVal - d.values[0].pointVal) / d.values[0].pointVal) * 100;
			   			f = (value % 1 == 0 ? 0 : 1);
			   			valueString = value.toFixed(f) + "%";
			   		<% elsif challenge.category == 'highest_cumulative' || challenge.category == 'lowest_cumulative' %>
			   			for (var j = 0; j < d.values.length; j++) { value += d.values[j].pointVal; }
			   			f = (value % 1 == 0 ? 0 : 1);
			   			valueString = value.toFixed(f) + " <%= challenge.units %>";
			   		<% end %>
			   		return (i+1) + ". " + d.name + " (" + valueString + ")";
			   })
			   .attr("id", function(d) {
			   		return "tracker-line-name-" + d.id;
				})
			   .attr("x", 0)
			   .attr("y", function(d, i) {
			   		return barStartY + i*(17 + barPadding);
			   })
			   .attr("font-size", "14px")
			   .on("mouseover", function(d) {
					d3.select(this).style("fill", highlightColor);

					// Highlight corresponding line
					svg.select("#tracker-line-" + d.id).style("stroke", highlightColor);
			   })
			   .on("mouseout", function(d) {
			   		d3.select(this).style("fill", "black");
			   		svg.select("#tracker-line-" + d.id).style("stroke", mainCircleColor);
			   });	


		barsSvg.append("text")
				.attr("id", "barsSvg-header")
				.attr("text-anchor", "middle")
				.attr("x", barsW / 2)
				.attr("y", yPadding)
				.text("Current Rankings");



		

	}

	function percentChange(d, i) {
		var percentChange = 0;
		if (i > 0) percentChange = (d[1] - dataset[i-1][1]) / dataset[i-1][1] * 100;
		return percentChange
	}

</script>

fitness/app/views/challenges/edit.html.erb
<% provide(:title, 'Edit Challenge') %>
<div class="sign-page-container" class="static-page-container">
	<div class="sign-form-container white-transparent-form">
		<h2 class="center">Edit Challenge</h2>

		<%= form_for(@challenge) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :title %>
			<%= f.text_field :title, class: "input-field", maxlength: "30"  %><br/>

			<%= f.label :description %>
			<%= f.text_area :description, class: "input-textarea" %><br/>

			<%= f.label :category, "Challenge Goal" %>
			<%= f.select :category, [
				['Highest Value', 'highest_value'], ['Lowest Value', 'lowest_value'], 
				['Highest Cumulative Total', 'highest_cumulative'], ['Lowest Cumulative Total', 'lowest_cumulative'], 
				['Greatest Increase in Value', 'greatest_increase'], ['Greatest Decrease in Value', 'greatest_decrease'], 
				['Greatest Percent Increase', 'greatest_percent_increase'], ['Greatest Percent Decrease', 'greatest_percent_decrease']], {}, class: "input-field", id: "challenge-select" %>


			<%= f.label :units %>
			<%= f.text_field :units, class: "input-field" %>

			<%= f.label :start_date %>
			<%= f.date_field :start_date, class: "input-field" %>

			<%= f.label :end_date %>
			<%= f.date_field :end_date, class: "input-field" %>

			<%= link_to '<button>Delete Challenge</button>'.html_safe, @challenge, method: :delete, data: { confirm: "Are you sure? This will permanently delete this challenge and all of its associated data." }, title: @challenge.title %>
			<%= f.submit "Save changes", class: "button" %>

		<% end %>
		
	</div>

</div>

fitness/app/views/challenges/new.html.erb
<% provide(:title, 'New Challenge') %>
<div class="sign-page-container" class="static-page-container">
	<div class="sign-form-container white-transparent-form">
		<h2 class="center">New Challenge</h2>

		<%= form_for(@challenge) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :title %>
			<%= f.text_field :title, class: "input-field required", maxlength: "30" %><br/>

			<%= f.label :description %>
			<%= f.text_area :description, class: "input-textarea" %>

			<%= f.label :category, "Challenge Goal" %>
			<%= f.select :category, [
				['Highest Value', 'highest_value'], ['Lowest Value', 'lowest_value'], 
				['Highest Cumulative Total', 'highest_cumulative'], ['Lowest Cumulative Total', 'lowest_cumulative'], 
				['Greatest Increase in Value', 'greatest_increase'], ['Greatest Decrease in Value', 'greatest_decrease'], 
				['Greatest Percent Increase', 'greatest_percent_increase'], ['Greatest Percent Decrease', 'greatest_percent_decrease']], {}, class: "input-field required", id: "challenge-select" %>


			<%= f.label :units %>
			<%= f.text_field :units, class: "input-field required" %>

			<%= f.label :start_date %>
			<%= f.date_field :start_date, class: "input-field required" %>

			<%= f.label :end_date %>
			<%= f.date_field :end_date, class: "input-field required" %>

			<%= f.submit "Create", class: "button sign-submit-button" %>

		<% end %>
	</div>

</div>

fitness/app/views/challenges/show.html.erb
<% provide(:title, @challenge.title) %>
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>

<table id="dashboard-container" border="none" width="100%">
	<tr>
		<td id="challenge-container" >
			<div id="challenge-vis-container" class="tile">
				<h3 class="center"><%= @challenge.title %></h3>

				<div id="tooltip" class="hidden">
					<span id="point-time"></span><br/>
					<span id="point-value"></span>
				</div>

				<div class="challenge-svg-container" id=<%= "challenge-svg-container-#{@challenge.id}" %>></div>
				<%= render 'challenges/challenge_vis', :challenge => @challenge %>		

				<div id="big-log-form-container">
					<%= form_for(@tracker, :class=>"big-log-form") do |f| %>
						<%= text_field_tag :data, nil, :class => 'input-field', :placeholder => @tracker.units, onkeypress: "return isNumberKey(event)" %>
						<%= f.submit "Log", class: "button log-button" %>
						<span class="last-log">Your last log: <%= time_ago_in_words(@tracker.updated_at) %> ago</span>
					<% end %>
				</div>		
			</div>
		</td>

		<td id="challenge-info-container">
			<div id="challenge-info-tile" class="tile">
				<h3 id="challenge-title-header" class="center">Challenge Info</h3>
				<div class="challenge-dates-container center-container">
					<%= (@challenge.start_date).strftime('%b %d, %Y') %> - <%= (@challenge.end_date).strftime('%b %d, %Y') %>
				</div>

				<h4 class="challenge-info-header">Description</h4>
				<p><%= @challenge.description %></p>

				<h4 class="challenge-info-header">Goal</h4>
				<p>
					<% if @challenge.category == 'highest_value' %>
					Highest Value Challenge: the winner of this challenge will be the member who has the highest value at the end date.
					<% elsif @challenge.category == 'lowest_value' %>
					Lowest Value Challenge: the winner of this challenge will be the member who has the lowest value at the end date.
					<% elsif @challenge.category == 'greatest_increase' %>
					Greatest Increase Challenge: the winner of this challenge will be the member who shows the greatest increase in value from the start date to the end date.	
					<% elsif @challenge.category == 'greatest_decrease' %>
					Greatest Decrease Challenge: the winner of this challenge will be the member who shows the greatest decrease in value from the start date to the end date.
					<% elsif @challenge.category == 'greatest_percent_increase' %>
					Greatest Percent Increase Challenge: the winner of this challenge will be the member who shows the greatest percent increase in value from the start date to the end date. The percent change is measured as a proportion of each member's starting value.
					<% elsif @challenge.category == 'greatest_percent_decrease' %>
					Greatest Percent Decrease Challenge: the winner of this challenge will be the member who shows the greatest percent decrease in value from the start date to the end date. The percent change is measured as a proportion of each member's starting value.
					<% elsif @challenge.category == 'highest_cumulative' %>
					Highest Cumulative Total Challenge: the winner of this challenge will be the member who shows the greatest cumulative value over the span of the challenge. 
					<% elsif @challenge.category == 'lowest_cumulative' %>
					Lowest Cumulative Total Challenge: the winner of this challenge will be the member who shows the lowest cumulative value over the span of the challenge. 
					<% end %>
				</p>

				<h4 class="challenge-info-header">Members</h4>
				<ul id="challenge-info-users">
					<%= render @challenge.users %>
				</ul>

				
				<div class="center-container">
					<%= form_for(@challenge, :url => {:action => "add_user"}, :class=>"challenge-user-form") do |f| %>
						<%= text_field_tag :user_email, nil, :class => 'input-field', :placeholder => "User Email" %>
						<%= f.submit "Add User", class: "button log-button" %>
					<% end %>
					<br/>
					<%= link_to '<button>Edit Challenge</button>'.html_safe, edit_challenge_path(@challenge) %>
					<%= link_to '<button>Leave Group</button>'.html_safe, remove_user_challenge_path(@challenge), :confirm => "Are you sure you want to leave this challenge group?", :method => 'patch' %>
				</div>
			</div>
		</td>
	</tr>

	<tr>
		<td id="challenge-messages-container" colspan="2">
			<div id="challenge-messages-tile" class="tile">
				<h3 class="center">Message Board</h3>
				<div id="messages-container">
					<%= render @challenge.messages %>
				</div>

				<table>
					<tr>
						<%= form_for([@challenge, @challenge.messages.build]) do |f| %>
						<td id="message-input-container"><%= f.text_field :body, class: "input-field", placeholder: "Write a message..." %></td>
						<td id="message-button-container"><%= f.submit "Submit", class: "button" %></td>
						<% end %>
					</tr>
				</table>

			</div>
		</td>
	</tr>
</table>
	