fitness/config/routes.rb
Fitness::Application.routes.draw do

  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :trackers, only: [:show, :create, :update, :destroy]
  resources :challenges, only: [:show, :new, :create, :edit, :update, :destroy] do
    member do
      patch :add_user
      patch :remove_user
    end
    resources :messages
  end

  root to: 'static_pages#home'
  match '/home',    to: 'static_pages#home',    via: 'get'  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/dashboard', to: 'users#show', via: 'get'
  match '/settings', to: 'users#edit', via: 'get'

end

fitness/app/views/layouts/_footer.html.erb
<footer id="footer">
	<span id="copyright">&copy; 2014 <%= title() %></span>

	<nav id="footer-nav">
		<ul class="pull-right">
			<%= link_to "<li>About</li>".html_safe, about_path %>
			<!--%= link_to "<li>Help</li>".html_safe, help_path %-->
		</ul>
	</nav>
</footer>

fitness/app/views/layouts/_header.html.erb
<header id="header">
  <a href=<%=home_path%>><h1 id="header-logo"><%= title() %></h1></a>
  <nav id="header-nav">
    <ul class="pull-right">

		<% if signed_in? %>
			<%= link_to "<li>Dashboard</li>".html_safe, dashboard_path %>
			<%= link_to "<li>Settings</li>".html_safe, settings_path %>
			<%= link_to "<li>Logout</li>".html_safe, signout_path, method: "delete" %>
		<% else %>
			<%= link_to "<li>Sign In</li>".html_safe, signin_path %>
		<% end %>

    </ul>
  </nav>
</header>

fitness/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

fitness/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>

		<link href='http://fonts.googleapis.com/css?family=Lato:300,400|Allan:700' rel='stylesheet' type='text/css'>

	</head>
	
	<body>
		<%= render 'layouts/header' %>
		<div id="container">
			<% flash.each do |key, value| %>
		    	<div class="alert alert-<%= key %>"><%= value %></div>
		    <% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<!--%= debug(params) if Rails.env.development? %-->
		</div>
	</body>
</html>